# Run Rails & Webpack concurrently
# Example file from webpack-rails gem
rails: bundle exec rails server -b 192.168.7.250
webpack: ./node_modules/.bin/webpack-dev-server --config config/webpack.config.js
